add rt to Sparta_LIBS
resolves
/bin/clang++ -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /include -fdebug-prefix-map==/usr/local/src/conda/map-untagged -fdebug-prefix-map==/usr/local/src/conda-prefix -O3 -DNDEBUG -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/lib -Wl,-rpath-link,/lib -L/lib CMakeFiles/Argos_dumper.dir/ArgosCollection_test.cpp.o -o Argos_dumper  ../../../sparta/libsparta.a ../../../sparta/simdb/libsimdb.a /lib/libhdf5.so -lsqlite3 /lib/libyaml-cpp.so.0.6.3 -lz -lpthread /lib/libboost_date_time.so.1.70.0 /lib/libboost_filesystem.so.1.70.0 /lib/libboost_iostreams.so.1.70.0 /lib/libboost_serialization.so.1.70.0 /lib/libboost_timer.so.1.70.0 /lib/libboost_program_options.so.1.70.0 /lib/libboost_chrono.so.1.70.0
/home/conda/feedstock_root/build_artifacts/map_1599066794883/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.5.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../../../sparta/libsparta.a(Scheduler.cpp.o): undefined reference to symbol 'clock_gettime@@GLIBC_2.2.5'
/home/conda/feedstock_root/build_artifacts/map_1599066794883/_build_env/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.5.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/conda/feedstock_root/build_artifacts/map_1599066794883/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/lib/librt.so.1: error adding symbols: DSO missing from command line
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [helios/pipeViewer/argos_dumper/Argos_dumper] Error 1

And it was also missing from test compilations that use clock_gettime